# Generated by Django 4.2.1 on 2023-05-09 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('looks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wardrobe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='look',
            name='clothing_items',
            field=models.ManyToManyField(to='wardrobe.clothingitem'),
        ),
        migrations.AddField(
            model_name='look',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
